# Generated by Django 4.1.6 on 2023-04-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0002_remove_cat_location_c_remove_dog_location_d_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="dogs",
            field=models.ManyToManyField(blank=True, to="petapp.dog"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_images/"),
        ),
    ]
