# Generated by Django 4.1.6 on 2023-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0004_alter_dog_id"),
        ("users", "0002_customuser_date_of_birth_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dogs",
            field=models.ManyToManyField(blank=True, to="petapp.dog"),
        ),
    ]
