# Generated by Django 4.1.6 on 2023-03-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0002_alter_pet_date_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
