# Generated by Django 4.1.6 on 2023-04-21 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="pet_images"),
                ),
                ("age", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("breed", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "pet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="petapp.pet",
                    ),
                ),
            ],
            bases=("petapp.pet",),
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "pet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="petapp.pet",
                    ),
                ),
            ],
            bases=("petapp.pet",),
        ),
    ]
