# Generated by Django 4.1.6 on 2023-04-21 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petapp", "0001_initial"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="cat",
        #     name="pet_ptr",
        # ),
        # migrations.RemoveField(
        #     model_name="dog",
        #     name="pet_ptr",
        # ),
        migrations.AddField(
            model_name="cat",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cat",
            name="breed",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AddField(
            model_name="cat",
            name="cat_id",
            field=models.CharField(
                default=" ", max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="cat",
            name="color",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AddField(
            model_name="cat",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cat",
            name="description",
            field=models.TextField(default=" ", max_length=1000),
        ),
        migrations.AddField(
            model_name="cat",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default=" ",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="cat",
            name="location",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AddField(
            model_name="cat",
            name="name",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AddField(
            model_name="cat",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pet_images"),
        ),
        migrations.AddField(
            model_name="cat",
            name="username",
            field=models.ForeignKey(
                default=" ",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dog",
            name="breed",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AddField(
            model_name="dog",
            name="color",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AddField(
            model_name="dog",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dog",
            name="description",
            field=models.TextField(default=" ", max_length=1000),
        ),
        migrations.AddField(
            model_name="dog",
            name="dog_id",
            field=models.CharField(
                default=" ", max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default=" ",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="location",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AddField(
            model_name="dog",
            name="name",
            field=models.CharField(default=" ", max_length=200),
        ),
        migrations.AddField(
            model_name="dog",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pet_images"),
        ),
        migrations.AddField(
            model_name="dog",
            name="username",
            field=models.ForeignKey(
                default=" ",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Pet",
        ),
    ]