# Generated by Django 4.1.6 on 2023-04-30 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cat",
            name="location_c",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="location_d",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="username",
        ),
        migrations.AddField(
            model_name="cat",
            name="county_c",
            field=models.CharField(
                choices=[
                    ("AB", "Alba"),
                    ("AR", "Arad"),
                    ("AG", "Arges"),
                    ("BC", "Bacau"),
                    ("BH", "Bihor"),
                    ("BN", "Bistrita-Nasaud"),
                    ("BT", "Botosani"),
                    ("BV", "Brasov"),
                    ("BR", "Braila"),
                    ("BZ", "Buzau"),
                    ("CS", "Caras-Severin"),
                    ("CL", "Calarasi"),
                    ("CJ", "Cluj"),
                    ("CT", "Constanta"),
                    ("CV", "Covasna"),
                    ("DB", "Dambovita"),
                    ("DJ", "Dolj"),
                    ("GL", "Galati"),
                    ("GR", "Giurgiu"),
                    ("GJ", "Gorj"),
                    ("HR", "Harghita"),
                    ("HD", "Hunedoara"),
                    ("IL", "Ialomita"),
                    ("IS", "Iasi"),
                    ("MM", "Maramures"),
                    ("MH", "Mehedinti"),
                    ("MS", "Mures"),
                    ("OT", "Olt"),
                    ("PH", "Prahova"),
                    ("SM", "Satu Mare"),
                    ("SJ", "Salaj"),
                    ("SB", "Sibiu"),
                    ("SV", "Suceava"),
                    ("TR", "Teleorman"),
                    ("TM", "Timis"),
                    ("TL", "Tulcea"),
                    ("VS", "Vaslui"),
                    ("VL", "Valcea"),
                    ("VN", "Vrancea"),
                ],
                default=" ",
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name="cat",
            name="status_c",
            field=models.CharField(
                choices=[("L", "Lost"), ("F", "Found"), ("A", "Adoption")],
                default=" ",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="county_d",
            field=models.CharField(
                choices=[
                    ("AB", "Alba"),
                    ("AR", "Arad"),
                    ("AG", "Arges"),
                    ("BC", "Bacau"),
                    ("BH", "Bihor"),
                    ("BN", "Bistrita-Nasaud"),
                    ("BT", "Botosani"),
                    ("BV", "Brasov"),
                    ("BR", "Braila"),
                    ("BZ", "Buzau"),
                    ("CS", "Caras-Severin"),
                    ("CL", "Calarasi"),
                    ("CJ", "Cluj"),
                    ("CT", "Constanta"),
                    ("CV", "Covasna"),
                    ("DB", "Dambovita"),
                    ("DJ", "Dolj"),
                    ("GL", "Galati"),
                    ("GR", "Giurgiu"),
                    ("GJ", "Gorj"),
                    ("HR", "Harghita"),
                    ("HD", "Hunedoara"),
                    ("IL", "Ialomita"),
                    ("IS", "Iasi"),
                    ("MM", "Maramures"),
                    ("MH", "Mehedinti"),
                    ("MS", "Mures"),
                    ("OT", "Olt"),
                    ("PH", "Prahova"),
                    ("SM", "Satu Mare"),
                    ("SJ", "Salaj"),
                    ("SB", "Sibiu"),
                    ("SV", "Suceava"),
                    ("TR", "Teleorman"),
                    ("TM", "Timis"),
                    ("TL", "Tulcea"),
                    ("VS", "Vaslui"),
                    ("VL", "Valcea"),
                    ("VN", "Vrancea"),
                ],
                default=" ",
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dogs_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="status_d",
            field=models.CharField(
                choices=[("L", "Lost"), ("F", "Found"), ("A", "Adoption")],
                default=" ",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
