# Generated by Django 4.1.6 on 2023-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0002_remove_cat_location_c_remove_dog_location_d_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="status_c",
            field=models.CharField(
                choices=[("L", "Lost"), ("F", "Found"), ("A", "Adoption")],
                default=" ",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="status_d",
            field=models.CharField(
                choices=[("L", "Lost"), ("F", "Found"), ("A", "Adoption")],
                default=" ",
                max_length=8,
            ),
        ),
    ]
