# Generated by Django 4.1.6 on 2023-04-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0002_remove_cat_pet_ptr_remove_dog_pet_ptr_cat_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="cat_id",
            field=models.CharField(
                default=1, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="dog_id",
            field=models.CharField(
                default=1, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
