# Generated by Django 4.1.6 on 2023-04-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petapp", "0003_alter_cat_cat_id_alter_dog_dog_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cat",
            name="pet_ptr",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="pet_ptr",
        ),
        migrations.AlterField(
            model_name="cat",
            name="cat_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cat",
            name="username",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="dog_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dog",
            name="username",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
