# Generated by Django 4.1.6 on 2023-04-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0003_cat_status_c_dog_status_d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
