# Generated by Django 4.1.6 on 2023-04-29 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petapp", "0004_alter_dog_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="username",
        ),
        migrations.AddField(
            model_name="dog",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dogs_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
